services:

  # SILO API
  api:
    image: ghcr.io/silo-app/silo-api:latest
    ports:
      - "8000:8000"
    depends_on:
    - postgres
    networks:
      - silo-net

  # PostgreSQL
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["/bin/bash", "pg_isready -U silo -d silo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - silo-net
    restart: unless-stopped

networks:
  silo-net:

volumes:
  postgres-data:
    