services:

  # SILO API
  api:
    container_name: silo-api
    env_file:
      - .env.production

  postgres:
    container_name: silo-postgres
    env_file:
      - .env.production

  frontend:
    container_name: silo-ui
    env_file:
      - .env.production