services:

  # SILO API
  api:
    container_name: silo-dev-api
    build: ../silo-api
    command: ["/app/.venv/bin/fastapi", "dev", "src/silo/main.py", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - .env.development
    environment:
      - SILO_LDAP_SERVER_URI=ldap://mokapi:389

  postgres:
    container_name: silo-dev-postgres
    env_file:
      - .env.development

  mokapi:
    image: mokapi/mokapi:latest
    container_name: silo-dev-mokapi
    ports:
      - "8080:8080"
      - "389:389"
    volumes:
      - ./mokapi:/mokapi:ro
    command: ["--providers-file-filename", "/mokapi"]
    networks:
      - silo-net
    restart: unless-stopped
    

networks:
  silo-net: